from .ubicacion import Ubicacion
from .obra_social import ObraSocial
from .laboratorio import Laboratorio
from .producto import Producto
from .cadena import Cadena
from .sucursal import Sucursal
from .persona import Persona
from .item_venta import ItemVenta
from .venta import Venta
